services:
  type: web
  name: api
  buildCommand: ./usr/src/app/entrypoint.sh
  env:
    - FLASK_APP=src/__init__.py
    - FLASK_DEBUG=1
    - FLASK_ENV=development
    - APP_SETTINGS=src.config.DevelopmentConfig
  startCommand: gunicorn -b 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker -t 300 src:app
  preDeployCommand: docker-entrypoint.sh postgres
  healthCheckPath: /
databases:
  - name: api_dev_xcdf
    plan: small
