version: '3.8'

services:
  type:: web
  name:api
  env: docker
  dockerfilePath: Dockerfile
  dockerCommand: /usr/src/app/entrypoint.sh
  dockerContext: /usr/src/app
  rootDir: app
  envVars:
    - key: FLASK_APP
      value: src/__init__.py 
    - key: FLASK_DEBUG
      value: 1 
    - key: FLASK_ENV
      value: development
    - key: DATABASE_URL
      value: postgresql://postgres:postgres@api-db:5432/api_dev_xcdf
    - key: PORT
      value: 5000
    - key: DATABASE_NAME
      value: api_dev_xcdf
    - key: CONNECTION_STRING 
      value: postgresql://postgres:postgres@api-db:5432/api_dev_xcdf

  
databases: 
   - name: postgresql
     databaseName: api_dev_xcdf
     dockerfilePath: Dockerfile
     dockerContext: ./src/db
     envVars:
        - key:  POSTGRES_USER
          value: api_dev_xcdf_user
        - key: POSTGRES_PASSWORD
          value: avmXZM8VrgZZa8onfxSc2ly0r7QTpHZa
        - key: CONNECTION_STRING 
          value: postgresql://postgres:postgres@api-db:5432/api_dev_xcdf
