services:
  # A Docker web service
  - type: web
    name: api
    runtime: docker
    rootDir: /usr/src/app
    dockerCommand: Dockerfile # optional (defaults to Dockerfile command)
    healthCheckPath: /
