databases:
  - name: api_dev
    databaseName: api_dev_xcdf


services:
  - type: web
    name: mysite
    buildCommand: "./Dockerfile"
    startCommand: "./entrypoint.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
