services:
  type: web
  name: api
  buildCommand: ./usr/src/app/entrypoint.sh
  env:
    - FLASK_APP=src/__init__.py
    - FLASK_DEBUG=1
    - FLASK_ENV=development
    - APP_SETTINGS=src.config.DevelopmentConfig
    - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
   - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
   - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev_xcdf
   - CONNECTION_STRING=postgresql://postgres:postgres@api-db:5432/api_dev_xcdf
  startCommand: gunicorn -b 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker -t 300 src:app
  preDeployCommand: docker-entrypoint.sh postgres
  healthCheckPath: /
  envVars:
    - key: APP_WORKERS
      value: "4"
databases:
  - name: api_dev_xcdf
    plan: small
